<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Inference for Proportions (Chapters 16-18) – Stat 102 Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Section-3-Means.html" rel="next">
<link href="./Section-1-Philosophy.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d9ea66fcd6c317012447f26e9c021348.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Section-2-Proportions.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Inference for Proportions (Chapters 16-18)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Stat 102 Notes</a> 
        <div class="sidebar-tools-main">
    <a href="./Stat-102-Notes.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Goals for STAT 102</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Section-1-Philosophy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Philosophy of Statistical Inference (Chapters 11-14)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Section-2-Proportions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Inference for Proportions (Chapters 16-18)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Section-3-Means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inference for Means (Chapters 19-22)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#inference-for-a-single-proportion-chapter-16" id="toc-inference-for-a-single-proportion-chapter-16" class="nav-link active" data-scroll-target="#inference-for-a-single-proportion-chapter-16"><span class="header-section-number">2.1</span> Inference for a Single Proportion (Chapter 16)</a>
  <ul class="collapse">
  <li><a href="#bootstrap-tests-for-one-proportion" id="toc-bootstrap-tests-for-one-proportion" class="nav-link" data-scroll-target="#bootstrap-tests-for-one-proportion"><span class="header-section-number">2.1.1</span> Bootstrap Tests for One Proportion</a></li>
  <li><a href="#bootstrap-confidence-intervals-for-one-proportion" id="toc-bootstrap-confidence-intervals-for-one-proportion" class="nav-link" data-scroll-target="#bootstrap-confidence-intervals-for-one-proportion"><span class="header-section-number">2.1.2</span> Bootstrap Confidence Intervals for One Proportion</a></li>
  <li><a href="#mathematical-model-for-a-proportion" id="toc-mathematical-model-for-a-proportion" class="nav-link" data-scroll-target="#mathematical-model-for-a-proportion"><span class="header-section-number">2.1.3</span> Mathematical Model for a Proportion</a></li>
  </ul></li>
  <li><a href="#inference-for-a-comparing-two-proportions-chapter-17" id="toc-inference-for-a-comparing-two-proportions-chapter-17" class="nav-link" data-scroll-target="#inference-for-a-comparing-two-proportions-chapter-17"><span class="header-section-number">2.2</span> Inference for a Comparing Two Proportions (Chapter 17)</a>
  <ul class="collapse">
  <li><a href="#randomization-tests-for-the-difference-in-proportions" id="toc-randomization-tests-for-the-difference-in-proportions" class="nav-link" data-scroll-target="#randomization-tests-for-the-difference-in-proportions"><span class="header-section-number">2.2.1</span> Randomization tests for the difference in proportions</a></li>
  <li><a href="#bootstrap-confidence-interval-for-the-difference-in-proportions" id="toc-bootstrap-confidence-interval-for-the-difference-in-proportions" class="nav-link" data-scroll-target="#bootstrap-confidence-interval-for-the-difference-in-proportions"><span class="header-section-number">2.2.2</span> Bootstrap confidence interval for the difference in proportions</a></li>
  <li><a href="#mathematical-model-for-the-difference-in-proportions" id="toc-mathematical-model-for-the-difference-in-proportions" class="nav-link" data-scroll-target="#mathematical-model-for-the-difference-in-proportions"><span class="header-section-number">2.2.3</span> Mathematical model for the difference in proportions</a></li>
  </ul></li>
  <li><a href="#inference-for-two-way-tables-chapter-18" id="toc-inference-for-two-way-tables-chapter-18" class="nav-link" data-scroll-target="#inference-for-two-way-tables-chapter-18"><span class="header-section-number">2.3</span> Inference for Two-Way Tables (Chapter 18)</a>
  <ul class="collapse">
  <li><a href="#expected-counts" id="toc-expected-counts" class="nav-link" data-scroll-target="#expected-counts"><span class="header-section-number">2.3.1</span> Expected Counts</a></li>
  <li><a href="#randomization-test" id="toc-randomization-test" class="nav-link" data-scroll-target="#randomization-test"><span class="header-section-number">2.3.2</span> Randomization Test</a></li>
  <li><a href="#mathematical-model" id="toc-mathematical-model" class="nav-link" data-scroll-target="#mathematical-model"><span class="header-section-number">2.3.3</span> Mathematical Model</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Inference for Proportions (Chapters 16-18)</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>So far, we’ve discussed randomization, bootstrap, and mathematical models as methods to approximate/describe a sampling distribution and quantify variability. Now, we turn to how these three methods can be used to answer research questions for different kinds of data. The appropriate method will depend on both the type of data and the research question of interest.</p>
<p>During our class, we’ll discuss two types of data: <strong>categorical</strong> and <strong>quantitative</strong>. Categorical data arise when the responses are categories. If you think about what is being measured on each unit in the sample, and could imagine checking a box to record the response, the data are categorical. For example:</p>
<p><br>
<br>
</p>
<p>We also have to consider the research question. The research question of interest will drive answers to the following:</p>
<ol type="1">
<li>Is a single variable being measured on each unit in the sample, or are two (or more) variables being recorded?</li>
</ol>
<p><br>
<br>
<br>
</p>
<ol start="2" type="1">
<li>If two or more variables are being recorded for each unit in the sample, can one be considered the <strong>response</strong> variable and the other(s) be considered <strong>explanatory</strong>?</li>
</ol>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<ol start="3" type="1">
<li>If a variable is categorical, does it have two possible outcomes (like yes/no) or more than two possible outcomes?</li>
</ol>
<div style="page-break-after: always;"></div>
<ol start="4" type="1">
<li>Is the research question focused around finding the answer to a yes/no question (like “Does a new teaching method improve student test scores?”) or around estimating a value (like “By how much do student test scores change if a new teaching method is introduced?”)?</li>
</ol>
<p><br>
<br>
<br>
<br>
</p>
<ol start="5" type="1">
<li>Were the data collected obtained using random sampling, random assignment, both, or neither? (this is not typically driven by the research question, but can impact our analysis method and will <strong>definitely</strong> impact the conclusions we can draw.)</li>
</ol>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>The answers to these questions will help us determine which method is most appropriate, as well as the specific analysis tool to implement that method. In this unit, we’re going to focus on categorical variables. We’re going to start with a single categorical variable measured on each unit in the sample, where that categorical variable has only two possible outcomes. From there we’ll move to two categorical variables measured on each unit (one explanatory, one response), again with only two possible outcomes for each. Finally, we’ll explore categorical variables with more than two possible outcomes.</p>
<div style="page-break-after: always;"></div>
<section id="inference-for-a-single-proportion-chapter-16" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="inference-for-a-single-proportion-chapter-16"><span class="header-section-number">2.1</span> Inference for a Single Proportion (Chapter 16)</h2>
<p>Our first scenario involves a single categorical variable measured on each unit in the sample, with only two possible outcomes.</p>
<p><br>
<br>
<br>
<br>
</p>
<section id="bootstrap-tests-for-one-proportion" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="bootstrap-tests-for-one-proportion"><span class="header-section-number">2.1.1</span> Bootstrap Tests for One Proportion</h3>
<p>When we discussed bootstrapping earlier, we were sampling (with replacement) from our sample data, because we wanted to understand the variability inherent to our statistic, <span class="math inline">\(\hat p\)</span>, assuming our sample is representative of all samples of the same size that could be drawn from the population. The goal of hypothesis testing is different: we want to understand the sampling distribution of <span class="math inline">\(\hat p\)</span> under the assumption</p>
<p><br>
<br>
<br>
<br>
<br>
</p>
<p>So, we need to repeatedly sample from a population with <span class="math inline">\(p=p_0\)</span>. We can do this by simulating data sets of the same size as original sample, assuming that <span class="math inline">\(p=p_0\)</span>. This is called a <strong>parametric bootstrap</strong>, because we are making an assumption about the value of the underlying parameter <span class="math inline">\(p\)</span> and we are assuming a particular distribution to generate our simulated data sets. From each simulated data set, we could calculate the resulting <span class="math inline">\(\hat p_{\hbox{\tiny{sim}}}\)</span>. Many simulated data sets will give us a good approximation for the distribution of <span class="math inline">\(\hat p\)</span> under our assumptions.</p>
<div style="page-break-after: always;"></div>
<p><strong>Example</strong>: Back to the babies picking the good guy or bad guy. We want to know if babies are more likely to pick the good guy puppet.</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>Under H<span class="math inline">\(_0\)</span>, 50% of babies will pick the good guy. We’ll assume this is true for all babies that could be tested. We’ll simulate 16 babies undergoing this test to get a sample proportion from the null distribution.</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>Let’s see how this works in R. We’ll start by setting up the original data, so we can calculate the test statistic.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data_baby<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">14</span>),<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">2</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>obs_prop<span class="ot">&lt;-</span><span class="fu">mean</span>(data_baby)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>obs_prop</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.875</code></pre>
</div>
</div>
<p>Next, we’ll set up the null model with 50% successes and 50% failures:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>para_boot<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">8</span>),<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">8</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>para_boot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0</code></pre>
</div>
</div>
<p>Now, we’ll repeatedly sample from the null distribution, and collect the resulting <span class="math inline">\(\hat p_{pb}\)</span> from each sample.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>numsim<span class="ot">&lt;-</span><span class="dv">100</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>boot.sample<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">sim=</span><span class="dv">1</span><span class="sc">:</span>numsim,<span class="at">stat=</span><span class="cn">NA</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boot.sample)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sim stat
1   1   NA
2   2   NA
3   3   NA
4   4   NA
5   5   NA
6   6   NA</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>numsim){</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  boot.sample<span class="sc">$</span>stat[i]<span class="ot">&lt;-</span><span class="fu">mean</span>(<span class="fu">sample</span>(para_boot,<span class="at">size=</span><span class="dv">16</span>,<span class="at">replace=</span><span class="cn">TRUE</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boot.sample)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sim   stat
1   1 0.3750
2   2 0.7500
3   3 0.6250
4   4 0.5000
5   5 0.7500
6   6 0.5625</code></pre>
</div>
</div>
<p>We can plot these <span class="math inline">\(\hat p_{pb}\)</span>, and see how unusual our observed test statistic is.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>boot.hist<span class="ot">&lt;-</span><span class="fu">ggplot</span>(boot.sample, <span class="fu">aes</span>(stat)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>boot.hist</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Section-2-Proportions_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We’ve got a plot, but how do we know exactly how many/what proportion of <span class="math inline">\(\hat p_{pb}\)</span> were greater than our observed test statistic, <span class="math inline">\(\hat p = 0.875\)</span>?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>count<span class="ot">&lt;-</span>(boot.sample<span class="sc">$</span>stat <span class="sc">&gt;=</span> obs_prop)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(count)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(count)<span class="sc">/</span>numsim</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>So, we have an estimated p-value of</p>
<p><br>
</p>
<p>What if we want to change the number of simulated data sets? Let’s try 1000. This gives an estimated p-value of</p>
<p><br>
</p>
<div style="page-break-after: always;"></div>
<p>Why is this an estimated p-value?</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>Why does this histogram not look bell-shaped?</p>
<p><br>
<br>
<br>
<br>
<br>
</p>
<p>Try Problem 5 in Chapter 16, and see if you can modify the Babies R code to re-create the histogram provided in the book. It might help to try the applet first and see what has to change there.</p>
<p><br>
<strong>Why Bootstrap?</strong></p>
<ul>
<li><p>Works for any sample size!</p></li>
<li><p>Intuitive way to explain what the p-value is actually measuring.</p></li>
</ul>
</section>
<section id="bootstrap-confidence-intervals-for-one-proportion" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="bootstrap-confidence-intervals-for-one-proportion"><span class="header-section-number">2.1.2</span> Bootstrap Confidence Intervals for One Proportion</h3>
<p>We’ve already done these! Recall that with a confidence interval, we’re not assuming the null hypothesis is true. Rather, our goal with the bootstrap is to characterize the variability of our statistic <span class="math inline">\(\hat p\)</span>.</p>
<p><br>
<br>
<br>
<br>
</p>
<div style="page-break-after: always;"></div>
</section>
<section id="mathematical-model-for-a-proportion" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3" class="anchored" data-anchor-id="mathematical-model-for-a-proportion"><span class="header-section-number">2.1.3</span> Mathematical Model for a Proportion</h3>
<p>Sometimes, the sampling distribution of <span class="math inline">\(\hat p\)</span> can be well-approximated using a normal distribution. The conditions which must be met are:</p>
<ul>
<li><p><br>
</p></li>
<li></li>
</ul>
<p><br>
<br>
<br>
</p>
<p>If these conditions are met, then</p>
<p><br>
<br>
<br>
<br>
<br>
</p>
<p>[Note: This result is just another way of stating the Central Limit Theorem when dealing with proportions! The success/failure condition is playing the role of the “sample is large enough” requirement of the CLT.]</p>
<p>Let’s think more about the standard error of <span class="math inline">\(\hat p\)</span>. Remember the <strong>standard error</strong> is</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>But this presents a problem. We don’t know <span class="math inline">\(p\)</span> (if we did, we wouldn’t be doing tests or confidence intervals)!</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
</p>
<div style="page-break-after: always;"></div>
<p>How is this going to play out in hypothesis tests?</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p><strong>Example</strong>: Look at Problem 3 in Chapter 16. The journalist claims more than 1/5 adults living in Seattle support defunding the police. Is this true?</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>To find the p-value, we can use R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">normTail</span>(<span class="at">m=</span><span class="dv">0</span>,<span class="at">s=</span><span class="dv">1</span>,<span class="at">U=</span><span class="fl">2.79</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Section-2-Proportions_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>pvalue<span class="ot">&lt;-</span><span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(<span class="fl">2.79</span>,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">1</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>pvalue</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.002635402</code></pre>
</div>
</div>
<p>Do you expect the p-value from the parametric bootstrap would be similar? Why or why not?</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>Let’s see.</p>
<div style="page-break-after: always;"></div>
<p>How is this going to play out in confidence intervals?</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p><strong>Example</strong>: Back to Chapter 16, problem 3. The journalist found that 159/650 Seattle residents support proposals to defund the police.</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>We can change the confidence level by changing <span class="math inline">\(z^*\)</span>, and using the <code>qnorm</code> function.</p>
<ul>
<li>90% confidence</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.05</span>,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.644854</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
<p><strong>Back to the bootstrap confidence interval…</strong></p>
<p>So far, we’ve seen <strong>bootstrap percentile confidence intervals</strong>. We calculated these directly from the bootstrapped <span class="math inline">\(\hat p_{\hbox{\tiny{boot}}}\)</span>. If we want a 90% confidence interval, we can find the 5<span class="math inline">\(^{th}\)</span> and 95<span class="math inline">\(^{th}\)</span> percentile values of the <span class="math inline">\(\hat p_{\hbox{\tiny{boot}}}\)</span> values.</p>
<p>We can also use the variability of the <span class="math inline">\(\hat p_{\hbox{\tiny{boot}}}\)</span> to calculate an estimate of the standard error of <span class="math inline">\(\hat p\)</span>, and then calculate the interval using the mathematical model approach. This is a <strong>bootstrap SE confidence interval</strong>.</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>This is a rough approximation, using the 68-95-99.7 Rule which says that 95% of the observed differences should be no farther than 2 SE from the true parameter (<span class="math inline">\(p\)</span>). To do this, the bootstrap histogram must be roughly symmetric and bell-shaped. So, it works for Chapter 16, problem 3; it doesn’t work with the babies.</p>
<p><br>
</p>
<p><strong>Why Z-Test/Z Confidence Intervals?</strong></p>
<ul>
<li>In many cases, works as well as simulation methods</li>
<li>Easy to calculate without technology/can do “back of the envelope” analyses</li>
<li>Z-scores and “estimate <span class="math inline">\(\pm\)</span> margin of error” are easily interpretable</li>
<li>Classical methods, used by scientists across disciplines</li>
</ul>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="inference-for-a-comparing-two-proportions-chapter-17" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="inference-for-a-comparing-two-proportions-chapter-17"><span class="header-section-number">2.2</span> Inference for a Comparing Two Proportions (Chapter 17)</h2>
<p>We now move on to consider situations in which two categorical variables are measured on each unit in the sample, and each variable has two possible values. In cases like these, typically one variable is considered the response and one variable is considered explanatory. The explanatory variable may be randomly assigned (like whether or not a subject swam with dolphins) or it may be merely observed (like smoking status). The two possible values of the explanatory variable lead to two groups, and we’re interested in comparing the population proportions that arise from these two groups. We’ll focus on the function of parameters <span class="math inline">\(p_1 - p_2\)</span>. The natural estimate of this is <span class="math inline">\(\hat p_1 - \hat p_2\)</span>: the difference in the sample proportions. We’ll be constructing hypothesis tests to compare <span class="math inline">\(p_1\)</span> to <span class="math inline">\(p_2\)</span> and finding confidence intervals to estimate <span class="math inline">\(p_1 - p_2\)</span>.</p>
<section id="randomization-tests-for-the-difference-in-proportions" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="randomization-tests-for-the-difference-in-proportions"><span class="header-section-number">2.2.1</span> Randomization tests for the difference in proportions</h3>
<p><strong>Example</strong>: Researchers are interested whether electrical brain stimulation will help with problem solving tasks. 40 volunteers were all trained to solve problems in a particular way. Half of the volunteers were randomly assigned to receive electrical stimulation and the other half received a sham stimulation (placebo). All volunteers were then presented with an unfamiliar problem and asked to solve it. The researchers are interested in testing whether the proportion able to solve the problem following electrical stimulation is greater than the proportion able to solve the problem without electrical stimulation.</p>
<p>There are a couple of different ways we could state the hypotheses of interest:</p>
<ul>
<li>H<span class="math inline">\(_0:\)</span></li>
</ul>
<p><br>
</p>
<ul>
<li>H<span class="math inline">\(_a:\)</span></li>
</ul>
<p><br>
</p>
<p>Recall that hypothesis tests work by assessing how unusual our observed data are, if the null hypothesis is really true. A very unusual result implies that observed data are not likely to have occurred under the null hypothesis. Randomization tests allow us to assess that unusualness by estimating the null distribution–a simulated distribution of what we could expect the distribution of <span class="math inline">\(\hat p_1 - \hat p_2\)</span> to look like if H<span class="math inline">\(_0\)</span> is true. We assume H<span class="math inline">\(_0\)</span> is true by recreating the randomization that occurred in the experiment.</p>
<p>Here are the data:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Solved</th>
<th>Not Solved</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sham</td>
<td></td>
<td></td>
<td>20</td>
</tr>
<tr class="even">
<td>Electrical</td>
<td></td>
<td></td>
<td>20</td>
</tr>
<tr class="odd">
<td>Total</td>
<td></td>
<td></td>
<td>40</td>
</tr>
</tbody>
</table>
<p>To demonstrate what the randomization test is doing, we need 40 cards. Why 40?</p>
<p><br>
</p>
<p>Of these cards, how many should be red and how many should be black? What do these represent?</p>
<p><br>
<br>
</p>
<p>We’ll shuffle, and deal into two stacks.</p>
<p><br>
<br>
<br>
</p>
<p>A randomization test is going through this shuffling/dealing over and over again, find the difference in proportions for each simulation.</p>
<p>Let’s look at this in the <a href="https://www.isi-stats.com/isi2nd/ISIapplets2021.html">applets</a>.</p>
<p>What do you notice about the null distribution? How unusual is the observed <span class="math inline">\(\hat p_1 - \hat p_2\)</span>?</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p><strong>Example</strong>: Try Problem 2 in Chapter 17. Set up the hypotheses and describe how a randomization test would work.</p>
<ul>
<li>How many cards are needed?</li>
<li>How many red? How many black?</li>
<li>How many should be dealt into each stack?</li>
<li>What would you calculate from each shuffle/deal?</li>
</ul>
<p>Let’s do this in R!</p>
<div style="page-break-after: always;"></div>
<p>First, we’ll need to set up the data. This is honestly the hardest part.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>VM<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">Treatment=</span><span class="st">"Vaccine"</span>,<span class="at">Response=</span><span class="st">"Malaria"</span>,<span class="at">obs=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">89</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(VM)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Treatment Response obs
1   Vaccine  Malaria   1
2   Vaccine  Malaria   2
3   Vaccine  Malaria   3
4   Vaccine  Malaria   4
5   Vaccine  Malaria   5
6   Vaccine  Malaria   6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>VN<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">Treatment=</span><span class="st">"Vaccine"</span>,<span class="at">Response=</span><span class="st">"NoMal"</span>,<span class="at">obs=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">203</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>CM<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">Treatment=</span><span class="st">"Control"</span>,<span class="at">Response=</span><span class="st">"Malaria"</span>,<span class="at">obs=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">106</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>CN<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">Treatment=</span><span class="st">"Control"</span>,<span class="at">Response=</span><span class="st">"NoMal"</span>,<span class="at">obs=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">41</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>malariadf<span class="ot">&lt;-</span><span class="fu">rbind</span>(VM,VN,CM,CN)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(malariadf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Treatment Response obs
1   Vaccine  Malaria   1
2   Vaccine  Malaria   2
3   Vaccine  Malaria   3
4   Vaccine  Malaria   4
5   Vaccine  Malaria   5
6   Vaccine  Malaria   6</code></pre>
</div>
</div>
<p>Next, we’ll calculate the observed difference in the proportion of children who contracted malaria between those who received the vaccine and those who received the control. To use the <code>diffmean</code> function, we need to load the <code>mosaic</code> package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>observed<span class="ot">&lt;-</span><span class="fu">diffmean</span>(Response <span class="sc">==</span> <span class="st">"Malaria"</span> <span class="sc">~</span> Treatment, <span class="at">data=</span>malariadf)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  diffmean 
-0.4162939 </code></pre>
</div>
</div>
<p>Now, we need to shuffle the vaccine/control treatment labels many times and calculate the difference in proportions of malaria for each shuffle. To do this, we’ll need the <code>mosaic</code> library but it’s already been loaded.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>malaria.null<span class="ot">&lt;-</span><span class="fu">do</span>(<span class="dv">1000</span>)<span class="sc">*</span><span class="fu">diffmean</span>(Response <span class="sc">==</span> <span class="st">"Malaria"</span> <span class="sc">~</span> <span class="fu">shuffle</span>(Treatment),<span class="at">data=</span>malariadf)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(malaria.null)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      diffmean
1  0.013255987
2  0.033710745
3  0.003028609
4 -0.068563042
5 -0.048108284
6 -0.007198770</code></pre>
</div>
</div>
<p>We’ll plot the null distribution, and to do this we’ll need the <code>ggplot2</code> library.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>malaria.null) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>diffmean)) <span class="sc">+</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Difference in proportions"</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> observed, <span class="at">linetype=</span><span class="dv">2</span>, <span class="at">color=</span><span class="st">"blue"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Section-2-Proportions_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finally, we can calculate the p-value by observing how unusual the observed difference in the proportions of malaria is under the null hypothesis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop</span>(<span class="sc">~</span>diffmean <span class="sc">&lt;=</span> observed, <span class="at">data=</span>malaria.null)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>prop_TRUE 
        0 </code></pre>
</div>
</div>
<p>Why are we considering less than or equal to be more extreme in this example?</p>
<p><br>
<br>
<br>
</p>
</section>
<section id="bootstrap-confidence-interval-for-the-difference-in-proportions" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="bootstrap-confidence-interval-for-the-difference-in-proportions"><span class="header-section-number">2.2.2</span> Bootstrap confidence interval for the difference in proportions</h3>
<p>As we saw with a single proportion, bootstrapping will allow us to estimate the variability of <span class="math inline">\(\hat p_1 - \hat p_2\)</span> without assuming the null hypothesis is true. With a single proportion, we drew repeated samples (with replacement) from our sample data, and from each bootstrap sample calculated <span class="math inline">\(\hat p_{\hbox{\tiny{boot}}}\)</span>. The distribution of the <span class="math inline">\(\hat p_{\hbox{\tiny{boot}}}\)</span> provided an estimation of the sampling distribution of <span class="math inline">\(\hat p\)</span>.</p>
<p>Now, with two samples, our observed statistic of interest is</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>Let’s go to R, and see how this works with the electrical stimulation example. We’ll start by setting up the data and calculating the observed difference in proportion of solved problems between electrical stimulation and control.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#original Sample 1 data (Electrical), creating a data set with 10 S (1) and 10 F (0)#</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>electrical<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">10</span>),<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">10</span>))</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co">#original Sample 2 data (Control), creating a data set with 6 S (1) and 14 F (0)#</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>control<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">6</span>),<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">14</span>))</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate and print the observed statistic, p-hat_E - p-hat_C#</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>obs_stat<span class="ot">&lt;-</span><span class="fu">mean</span>(electrical)<span class="sc">-</span><span class="fu">mean</span>(control)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>obs_stat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2</code></pre>
</div>
</div>
<p>Now, we’ll repeatedly sample with replacement separately from each group. First we need to set up a place to store our summaries from each resample.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Set up an empty data set with 4 columns: sim number, p_hat_boot_E, p_hat_boot_C, diff#</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>boot.samples<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">sim=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>,<span class="at">stat_E=</span><span class="cn">NA</span>,<span class="at">stat_C=</span><span class="cn">NA</span>, <span class="at">diff=</span><span class="cn">NA</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boot.samples)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sim stat_E stat_C diff
1   1     NA     NA   NA
2   2     NA     NA   NA
3   3     NA     NA   NA
4   4     NA     NA   NA
5   5     NA     NA   NA
6   6     NA     NA   NA</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#For each row in the data set, draw a bootstrap sample from Sample 1 and Sample 2 and find#</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># p_hat_boot_E and p_hat_boot_C #</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  boot.samples<span class="sc">$</span>stat_E[i]<span class="ot">&lt;-</span><span class="fu">mean</span>(<span class="fu">sample</span>(electrical,<span class="at">size=</span><span class="dv">20</span>,<span class="at">replace=</span><span class="cn">TRUE</span>))</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  boot.samples<span class="sc">$</span>stat_C[i]<span class="ot">&lt;-</span><span class="fu">mean</span>(<span class="fu">sample</span>(control,<span class="at">size=</span><span class="dv">20</span>,<span class="at">replace=</span><span class="cn">TRUE</span>))</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boot.samples)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sim stat_E stat_C diff
1   1   0.40   0.25   NA
2   2   0.45   0.20   NA
3   3   0.60   0.40   NA
4   4   0.35   0.35   NA
5   5   0.35   0.15   NA
6   6   0.50   0.30   NA</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Now find the differences#</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>boot.samples<span class="sc">$</span>diff<span class="ot">&lt;-</span>boot.samples<span class="sc">$</span>stat_E <span class="sc">-</span> boot.samples<span class="sc">$</span>stat_C</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boot.samples)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sim stat_E stat_C diff
1   1   0.40   0.25 0.15
2   2   0.45   0.20 0.25
3   3   0.60   0.40 0.20
4   4   0.35   0.35 0.00
5   5   0.35   0.15 0.20
6   6   0.50   0.30 0.20</code></pre>
</div>
</div>
<p>Now let’s plot the bootstrap distribution.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>boot.hist<span class="ot">&lt;-</span><span class="fu">ggplot</span>(boot.samples, <span class="fu">aes</span>(diff)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.05</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>boot.hist</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Section-2-Proportions_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Notice where this distribution is centered!</p>
<p><br>
</p>
<div style="page-break-after: always;"></div>
<p>We are re-using this example, since we’ve already carried out the randomization test in the applet. By doing so we are ignoring (maybe) the research question. But, we’re doing both a randomization test and confidence interval so that we can compare the resulting sampling distributions of <span class="math inline">\(\hat p_1 - \hat p_2\)</span>. What is different? What’s the same?</p>
<p><br>
<br>
<br>
<br>
<br>
</p>
<p>Now that we have the bootstrap distribution, we can find the bootstrap percentile confidence interval. Let’s do a 90% interval.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#start by ranking the bootstrap differences from smallest to largest #</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>rankdiff<span class="ot">&lt;-</span><span class="fu">sort</span>(boot.samples<span class="sc">$</span>diff)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Print out just the first few#</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rankdiff)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.35 -0.20 -0.20 -0.20 -0.20 -0.20</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Lower endpoint is the 5th percentile (90% confidence)#</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>lower<span class="ot">&lt;-</span>rankdiff[<span class="dv">50</span>]</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>lower</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.05</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Upper endpoint is the 950th percentile (90% confidence)#</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>upper<span class="ot">&lt;-</span>rankdiff[<span class="dv">950</span>]</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>upper</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.45</code></pre>
</div>
</div>
<p><br>
<br>
<br>
</p>
<div style="page-break-after: always;"></div>
<p>Because our bootstrap distribution is relatively bell-shaped, we could also a calculate a rough 95% boostrap SE confidence interval.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>SE<span class="ot">&lt;-</span><span class="fu">sd</span>(rankdiff)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>SE</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1542495</code></pre>
</div>
</div>
<p><br>
<br>
<br>
<br>
<br>
</p>
</section>
<section id="mathematical-model-for-the-difference-in-proportions" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="mathematical-model-for-the-difference-in-proportions"><span class="header-section-number">2.2.3</span> Mathematical model for the difference in proportions</h3>
<p>For a single proportion, we needed two conditions to be met to ensure the sampling distribution of <span class="math inline">\(\hat p\)</span> is approximately normal:</p>
<ul>
<li><p><br>
</p></li>
<li><p><br>
<br>
</p></li>
</ul>
<p>If these conditions are met, then</p>
<p><br>
<br>
<br>
</p>
<p>We must meet similar conditions to ensure the sampling distribution of <span class="math inline">\(\hat p_1 - \hat p_2\)</span> is approximately normal:</p>
<ul>
<li><p><br>
<br>
</p></li>
<li><p><br>
<br>
</p></li>
</ul>
<p>If these conditions are met, then</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>Like before we don’t know <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span>, so we’ll use our best guess. And, like before, our best guess will change depending on whether we’re constructing a confidence interval or carrying out a hypothesis test.</p>
<p>How is this going to play out in a hypothesis test?</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<div style="page-break-after: always;"></div>
<p><strong>Example (17.5)</strong>: (Aside: why can’t we do the electrical stimuation example again?). A 2021 Gallup poll surveyed 3941 students pursuing a bachelor’s degree and 2064 students pursuing an associate’s degree. The survey found that 51% of the bachelor’s students (2010) and 44% of the associate’s students (908) said that COVID-19 will negatively impact their ability to complete the degree. We want to decide whether the proportion of bachelor’s students who believe the pandemic will negatively impact degree completion is different from the proportion of associate’s students who believe they will be negatively affected. Let <span class="math inline">\(p_B\)</span> be the proportion of bachelor’s students who believe they’ll be negatively affected and let <span class="math inline">\(p_A\)</span> be the proportion of associate’s students who believe they’ll be negatively affected.</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>To visualize the p-value:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">normTail</span>(<span class="at">m=</span><span class="dv">0</span>,<span class="at">s=</span><span class="dv">1</span>,<span class="at">L=</span><span class="sc">-</span><span class="fl">5.15</span>, <span class="at">U=</span><span class="fl">5.15</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Section-2-Proportions_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>And to get the p-value:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">5.15</span>,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">1</span>)<span class="sc">+</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(<span class="fl">5.15</span>,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.604865e-07</code></pre>
</div>
</div>
<p><br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>How is this going to play out in a confidence interval?</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
</p>
<div style="page-break-after: always;"></div>
<p><strong>Example(17.9)</strong>: A Kaiser Family Foundation poll for US adults in 2019 found that 79% of Democrats, 55% of Independents, and 24% of Republicans supported a generic “National Health Plan.” There were 347 Democrats, 298 Republicans, and 617 Independents surveyed (Foundation, 2019). We want to estimate the difference between the proportion of Democrats and Independents who support a National Health Plan.</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p><strong>What impacts the width of a confidence interval?</strong></p>
<p>There are three main things that impact the width of a confidence interval:</p>
<ul>
<li>Confidence level</li>
</ul>
<p><br>
</p>
<ul>
<li>Sample size</li>
</ul>
<p><br>
</p>
<ul>
<li>Standard Error</li>
</ul>
<p><br>
</p>
<p>No matter what method we use to calculate the confidence interval, the <strong>confidence level</strong> is a statement about the long run percentage of confidence intervals that would succeed in capturing the true value of the parameter. What does this mean? <a href="https://www.isi-stats.com/isi2nd/ISIapplets2021.html">Applet</a></p>
<p><br>
</p>
<p><strong>Hypothesis tests vs.&nbsp;Confidence Intervals</strong></p>
<p>While we should be matching analysis method to the research question, there is a nice relationship between hypothesis tests and confidence intervals. Recall that confidence intervals give a set of plausible values for the unknown parameter.</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
</section>
</section>
<section id="inference-for-two-way-tables-chapter-18" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="inference-for-two-way-tables-chapter-18"><span class="header-section-number">2.3</span> Inference for Two-Way Tables (Chapter 18)</h2>
<p>So far, we’ve considered categorical variables with only two possible outcomes: success and failure. Many categorical variables have more than two possible outcomes, so we can’t easily define the proportion of “successes.” Instead, we’ll summarize categorical data with more than two levels using two-way tables. In this class, we’re still going to restrict ourselves to only two variables (often explanatory and response, but not necessarily), both with two or more levels. However, there are certainly statistical methods for more complicated situations.</p>
<p>Typically, research questions focus on how the proportions of the possible outcomes in the response variable change (or don’t) across the levels of the explanatory variable. However, we can also consider questions about a single variable with more than two outcomes (are the possible outcomes all equally likely? do the possible outcomes follow a particular pattern?) or just whether the two categorical variables are independent or dependent without assigning an explanatory/response relationship. Due to the structure of the variable(s), there really isn’t a population parameter of interest. We can’t (usually) make a function of proportion of successes that makes sense to estimate, like we can with <span class="math inline">\(p_1 - p_2\)</span>. That means we’ll be considering only tests, not confidence intervals. We’ll focus on the randomization test and the mathematical model approach. Both methods start with the same set-up.</p>
<div style="page-break-after: always;"></div>
<p><strong>Example</strong>: When surveys are administered, we hope that the respondents give accurate answers. Does the mode of survey delivery affect this? Schober et al (2015) investigated this question. They had 147 people who agreed to be interviewed on an iPhone, and they were randomly assigned to one of three interview modes: human voice, automated voice, text. One question asked was whether they exercise less than once per week during a typical week (a yes is mostly likely considered socially undesirable). The explanatory variable here is survey mode and the response is whether or not the respondent said yes. Here are the data:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Text</th>
<th>Human Voice</th>
<th>Automated Voice</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exercise Yes</td>
<td>34</td>
<td>21</td>
<td>20</td>
<td>75</td>
</tr>
<tr class="even">
<td>Exercise No</td>
<td>124</td>
<td>139</td>
<td>139</td>
<td>402</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>158</td>
<td>160</td>
<td>159</td>
<td>477</td>
</tr>
</tbody>
</table>
<p>Based on these data, it looks like the answer to the question does change depending on survey mode, with respondents more likely to say yes via text. However, we don’t know if this result could have happened by chance.</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<section id="expected-counts" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="expected-counts"><span class="header-section-number">2.3.1</span> Expected Counts</h3>
<p>We don’t expect the proportion of `yes’ to be exactly the same across all survey modes, but we want to know if these vary enough to convince us that survey mode and answer are not independent. To do this, we need to find for each cell in the table.</p>
<div style="page-break-after: always;"></div>
<p>Again, here are the observed data</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Text</th>
<th style="text-align: center;">Human Voice</th>
<th style="text-align: center;">Automated Voice</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exercise Yes</td>
<td style="text-align: center;">34</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">75</td>
</tr>
<tr class="even">
<td>Exercise No</td>
<td style="text-align: center;">124</td>
<td style="text-align: center;">139</td>
<td style="text-align: center;">139</td>
<td style="text-align: center;">402</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: center;">158</td>
<td style="text-align: center;">160</td>
<td style="text-align: center;">159</td>
<td style="text-align: center;">477</td>
</tr>
</tbody>
</table>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Text</th>
<th>Human Voice</th>
<th>Auto Voice</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exercise Yes</td>
<td>34 (_____)</td>
<td>21 (_____)</td>
<td>20 (_____)</td>
<td>75</td>
</tr>
<tr class="even">
<td>Exercise No</td>
<td>124 (_____)</td>
<td>139 (_____)</td>
<td>139 (_____)</td>
<td>402</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>158</td>
<td>160</td>
<td>159</td>
<td>477</td>
</tr>
</tbody>
</table>
<div style="page-break-after: always;"></div>
<p>So now the key question…are the observed and expected cell counts different enough?</p>
<ul>
<li>Cell(1,1) obs - exp = 34 -</li>
<li>Cell(1,2) obs - exp = 21 -</li>
<li>Cell(1,3) obs - exp = 20 -</li>
<li>Cell(2,1) obs - exp = 124 -</li>
<li>Cell(2,2) obs - exp = 139 -</li>
<li>Cell(2,3) obs - exp = 139 -</li>
</ul>
<p><br>
<br>
<br>
<br>
</p>
<p>New test statistic!</p>
<p><br>
<br>
<br>
<br>
<br>
</p>
<p>In our example:</p>
<ul>
<li>Cell(1,1) (obs - exp)<span class="math inline">\(^2\)</span>/exp = <span class="math inline">\((34 - 24.84)^2/(24.84) = 9.16^2/24.84 = 3.3778\)</span></li>
<li>Cell(1,2) (obs - exp)<span class="math inline">\(^2\)</span>/exp = <span class="math inline">\((21 - 25.16)^2/(25.16) = (-4.16)^2/25.16 = 0.6878\)</span></li>
<li>Cell(1,3) (obs - exp)<span class="math inline">\(^2\)</span>/exp = <span class="math inline">\((20 - 25)^2/(25) = (-5)^2/25 = 1\)</span></li>
<li>Cell(2,1) (obs - exp)<span class="math inline">\(^2\)</span>/exp = <span class="math inline">\((124 - 133.16)^2/(133.16) = (-9.16)^2/133.16 = 0.6301\)</span></li>
<li>Cell(2,2) (obs - exp)<span class="math inline">\(^2\)</span>/exp = <span class="math inline">\((139 - 134.84)^2/(134.84) = 4.16^2/134.84 = 0.1283\)</span></li>
<li>Cell(2,3) (obs - exp)<span class="math inline">\(^2\)</span>/exp = <span class="math inline">\((139 - 134)^2/(134) = 5^2/134 =0.3731\)</span></li>
</ul>
<p><br>
<br>
</p>
<p>To see if this is ‘big’ we need the sampling distribution of our new test statistic. We can estimate that sampling distribution using either a randomization test or the mathematical model approach.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="randomization-test" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="randomization-test"><span class="header-section-number">2.3.2</span> Randomization Test</h3>
<p>The randomization test for a two-way table works just like it does with two samples. We’ll randomize by shuffling and dealing/assigning the 75 yes answers and 402 no answers to the three survey modes at random.</p>
<ul>
<li>How many colors of cards?</li>
</ul>
<p><br>
<br>
</p>
<ul>
<li>How many stacks to deal them into? How many in each stack?</li>
</ul>
<p><br>
<br>
</p>
<ul>
<li>What do we find for each deal/shuffle?</li>
</ul>
<p><br>
<br>
</p>
<p><a href="https://www.isi-stats.com/isi2nd/ISIapplets2021.html">Applet</a></p>
<p><br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>Conclusion:</p>
<div style="page-break-after: always;"></div>
</section>
<section id="mathematical-model" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="mathematical-model"><span class="header-section-number">2.3.3</span> Mathematical Model</h3>
<p>Based on what we just observed in the applet, the normal distribution is not going to be a good approximation to sampling distribution. It turns out this test statistic follows a different mathematical distribution, the <strong>chi-squared distribution</strong> (proof: see STAT 462). The normal distribution has two parameters that determine its shape: the mean (<span class="math inline">\(\mu\)</span>) and standard deviation (<span class="math inline">\(\sigma\)</span>). The shape of the chi-square distribution is determined by a parameter called the . Figure 18.2 on page 307 shows how the shape of the distribution changes depending on the df.</p>
<p>So how can we use this?</p>
<p><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</p>
<p>Again, we have conditions that need to be met for the mathematical model to be a good approximation:</p>
<ul>
<li><p><br>
</p></li>
<li><p><br>
</p></li>
</ul>
<p><strong>Example</strong>: Let’s go back and do the survey mode example using the mathematical model approach. First, we’ll need to check the conditions are met:</p>
<ul>
<li><p><br>
</p></li>
<li><p><br>
</p></li>
</ul>
<p><br>
</p>
<p>To find the p-value, we can use the R function <code>pchisq()</code>. Like <code>pnorm</code> it gives area to the left. So,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fl">6.1971</span>,<span class="at">df=</span><span class="dv">2</span>,<span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04511457</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
<p>We can also do this directly in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>surveymode<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"surveymode.csv"</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co">#make a table#</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>mode<span class="ot">&lt;-</span><span class="fu">table</span>(surveymode<span class="sc">$</span>Response,surveymode<span class="sc">$</span>Mode)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="co">#see the table, note alphabetical order#</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>mode</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
      Avoice Hvoice Text
  No     139    139  124
  Yes     20     21   34</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Chi-square mathematical model test#</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(mode)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  mode
X-squared = 6.0069, df = 2, p-value = 0.04962</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Chi-square randomization test#</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(mode,<span class="at">simulate.p.value=</span><span class="cn">TRUE</span>, <span class="at">B=</span><span class="dv">1000</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with simulated p-value (based on 1000
    replicates)

data:  mode
X-squared = 6.0069, df = NA, p-value = 0.05095</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Section-1-Philosophy.html" class="pagination-link" aria-label="Philosophy of Statistical Inference (Chapters 11-14)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Philosophy of Statistical Inference (Chapters 11-14)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Section-3-Means.html" class="pagination-link" aria-label="Inference for Means (Chapters 19-22)">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inference for Means (Chapters 19-22)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>